---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
# NOTE: fmhfunprofiler is not available on bioconda/conda-forge.
# this container is modified by a conditional process if the conda or mamba profile is used.
channels:
  - conda-forge
  - bioconda
dependencies:
  - python
  - pip
  - conda-forge::wget
  - conda-forge::unzip
  - conda-forge::bc
  - conda-forge::git
  - conda-forge::setuptools
  - conda-forge::wheel
  - conda-forge::pandas
  - bioconda::sourmash
  - bioconda::biom-format=2.1.7
